DROP TABLE IF EXISTS PRODUCT_LEVEL_INVENTORY;


CREATE TABLE PRODUCT_LEVEL_INVENTORY (
	CATEGORY VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	MRP INT NOT NULL,
	DISCOUNT_PERCENT INT NOT NULL,
	AVAILABLE_QUANTITY INT NOT NULL,
	DISCOUNTED_SELLING_PRICE INT NOT NULL,
	WEIGHT_IN_GMS INT NOT NULL,
	OUT_OF_STOCK VARCHAR(50) NOT NULL,
	QUANTITY INT
);

select * from product_level_inventory;


COPY PRODUCT_LEVEL_INVENTORY (
	CATEGORY,
	NAME,
	MRP,
	DISCOUNT_PERCENT,
	AVAILABLE_QUANTITY,
	DISCOUNTED_SELLING_PRICE,
	WEIGHT_IN_GMS,
	OUT_OF_STOCK,
	QUANTITY
)
FROM
	'C:\Users\kaif\OneDrive\Desktop\zepto_v1111.csv' DELIMITER ',' CSV HEADER;

SELECT
	*
FROM
	PRODUCT_LEVEL_INVENTORY;


                                   --View all products

--View all products

SELECT
	NAME
FROM
	PRODUCT_LEVEL_INVENTORY;
	

 -- Limit 10 rows
 
 SELECT
	*
FROM
	PRODUCT_LEVEL_INVENTORY
LIMIT
	10;
	

 --Category-level listing

SELECT DISTINCT
	CATEGORY
FROM
	PRODUCT_LEVEL_INVENTORY;
	

--Count products per category

SELECT
	CATEGORY,
	COUNT(*) AS TOTAL_PRODUCTS
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	TOTAL_PRODUCTS DESC;


									--Price Analysis

--Top 10 highest MRP products	

SELECT
	NAME,
	CATEGORY,
	MRP
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	MRP DESC
LIMIT
	10;

--Top 10 lowest discounted price products

SELECT
	NAME,
	CATEGORY,
	DISCOUNTED_SELLING_PRICE
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	DISCOUNTED_SELLING_PRICE ASC
LIMIT
	10;


--Average MRP per category

SELECT
	CATEGORY,
	ROUND(AVG(MRP), 3) AS AVG_MRP_PER_CATEGORY
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY;


                                --Stock Status

--Count out-of-stock products

SELECT
	CATEGORY,
	product,
	COUNT(*) AS OUT_OF_STOCK_COUNT
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	OUT_OF_STOCK = 'TRUE'
GROUP BY
	CATEGORY,
	product;

--Show products where availableQuantity < 5

ALTER TABLE PRODUCT_LEVEL_INVENTORY
RENAME NAME TO PRODUCT;

SELECT
	*
FROM
	PRODUCT_LEVEL_INVENTORY;

SELECT
	PRODUCT,
	AVAILABLE_QUANTITY
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	AVAILABLE_QUANTITY < 5;


--Percentage of out-of-stock products

SELECT
	COUNT(
		CASE
			WHEN OUT_OF_STOCK = 'TRUE' THEN 1
		END
	) * 100.0 / COUNT(*) AS OUT_OF_STOCK_PERCENTAGE
FROM
	PRODUCT_LEVEL_INVENTORY;

                                       -- Discount Insights


--Products with discount > 20%

SELECT
	CATEGORY,
	DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	DISCOUNT_PERCENT > 21
ORDER BY
	DISCOUNT_PERCENT DESC;

--Average discount per category

SELECT
	CATEGORY,
	ROUND(AVG(DISCOUNT_PERCENT), 2) AS CATEGORY_DISCOUNT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY;

--Highest  discounted product

SELECT
	PRODUCT,
	CATEGORY,
	DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	DISCOUNT_PERCENT DESC
LIMIT
	1;



SELECT
	*
FROM
	PRODUCT_LEVEL_INVENTORY;

SELECT DISTINCT
	CATEGORY
FROM
	PRODUCT_LEVEL_INVENTORY;



						  	      --Revenue Simulation

--Total potential revenue

SELECT
	SUM(MRP) AS TOTAL_REVENUE
FROM
	PRODUCT_LEVEL_INVENTORY;

--Revenue per category

SELECT
	CATEGORY,
	SUM(MRP) AS CATEGORY_WISE_REVENUE
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	(CATEGORY)
ORDER BY
	CATEGORY_WISE_REVENUE DESC;


--Top 5 revenue-generating categories

SELECT
	CATEGORY,
	SUM(MRP) AS CATEGORY_WISE_REVENUE
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	(CATEGORY)
ORDER BY
	CATEGORY_WISE_REVENUE DESC
LIMIT
	5;

--Top 20 revenue-generating products

SELECT
	PRODUCT,
	SUM(MRP) AS TOP_20_REVENUE_PRODUCTS
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	(PRODUCT)
ORDER BY
	TOP_20_REVENUE_PRODUCTS DESC
LIMIT
	20;

 
									 --Profit Simulation

									 
--Estimated profit per product (Cost = 70% of MRP)
SELECT
	PRODUCT,
	MRP,
	ROUND(MRP * 0.30, 2) AS PROFIT_MARGIN
FROM
	PRODUCT_LEVEL_INVENTORY
	ORDER BY PROFIT_MARGIN DESC;



		 
--Category-wise profit

SELECT
	*
FROM
	PRODUCT_LEVEL_INVENTORY;

ALTER TABLE PRODUCT_LEVEL_INVENTORY
ADD COLUMN TOTAL_PROFIT NUMERIC(10, 2);

UPDATE PRODUCT_LEVEL_INVENTORY
SET
	TOTAL_PROFIT = MRP * 0.30;

SELECT
	CATEGORY,
	SUM(TOTAL_PROFIT) AS CATEGORY_WISE_PROFIT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	CATEGORY_WISE_PROFIT DESC;


                                         --Discount Impact Analysis	
										 

--Compare average MRP vs average discounted price by category

SELECT
	CATEGORY,
	ROUND(AVG(MRP), 3) AS AVG_MRP,
	ROUND(AVG(DISCOUNT_PERCENT), 3) AS AVG_DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	(CATEGORY);


--Category with highest average discount
SELECT
	CATEGORY,
	ROUND(AVG(DISCOUNT_PERCENT), 3) AS AVG_DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	(CATEGORY);


--Correlation between discountPercent and availableQuantity

SELECT
	PRODUCT,
	DISCOUNT_PERCENT,
	AVAILABLE_QUANTITY
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	DISCOUNT_PERCENT,
	AVAILABLE_QUANTITY DESC;

SELECT
	CATEGORY,
	CORR(DISCOUNT_PERCENT, AVAILABLE_QUANTITY) AS CORRELATION_VALUE
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	CORRELATION_VALUE DESC;

  --all correlation_values are random--


--Weight-Based Pricing

SELECT
	PRODUCT,
	WEIGHT_IN_GMS,
	MRP
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	WEIGHT_IN_GMS DESC;


--Price per gram calculation
SELECT
	WEIGHT_IN_GMS
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	WEIGHT_IN_GMS = 0;


SELECT
	PRODUCT,
	MRP,
	WEIGHT_IN_GMS,
	MRP / NULLIF(WEIGHT_IN_GMS, 0) AS PRICE_PER_GRAM
FROM
	PRODUCT_LEVEL_INVENTORY;
    


--Most expensive per gram products

SELECT
	PRODUCT,
	MRP,
	WEIGHT_IN_GMS,
	MRP / WEIGHT_IN_GMS AS PRICE_PER_GRAM
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	MRP IS NOT NULL
	AND WEIGHT_IN_GMS IS NOT NULL
	AND WEIGHT_IN_GMS <> 0
ORDER BY
	PRICE_PER_GRAM DESC;
  
--Cheapest per gram products
SELECT
	PRODUCT,
	MRP,
	WEIGHT_IN_GMS,
	MRP / WEIGHT_IN_GMS AS PRICE_PER_GRAM
FROM	
	PRODUCT_LEVEL_INVENTORY
WHERE
	MRP IS NOT NULL
	AND WEIGHT_IN_GMS IS NOT NULL
	AND WEIGHT_IN_GMS <> 0
ORDER BY
	PRICE_PER_GRAM ASC;



                                   ---Revenue Ranking & Top Products---
								   
								   
--Calculate the Potential Revenue for Every Product
WITH
	PRODUCTREVENUE AS (
		SELECT
			CATEGORY,
			PRODUCT,
			AVAILABLE_QUANTITY,
			DISCOUNTED_SELLING_PRICE,
			(AVAILABLE_QUANTITY * DISCOUNTED_SELLING_PRICE) AS POTENTIAL_REVENUE
		FROM
			PRODUCT_LEVEL_INVENTORY
		WHERE
			OUT_OF_STOCK = 'FALSE'
	)
SELECT
	*
FROM
	PRODUCTREVENUE
ORDER BY
	POTENTIAL_REVENUE DESC;


--Rank Products by Revenue Within Each Category

SELECT
	CATEGORY,
	PRODUCT,
	DISCOUNTED_SELLING_PRICE * QUANTITY AS SELLING_WISE_PRODUCT_REVENUE,
	DENSE_RANK() OVER (
		PARTITION BY
			CATEGORY
		ORDER BY
			DISCOUNTED_SELLING_PRICE * QUANTITY DESC
	) AS CATEGORY_RANK
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	OUT_OF_STOCK = 'FALSE';

--Extract Only the Top 3 Products Per Category
 
WITH
	RANKED_PRODUCTS AS (
		SELECT
			CATEGORY,
			PRODUCT,
			DISCOUNTED_SELLING_PRICE * QUANTITY AS SELLING_WISE_PRODUCT_REVENUE,
			DENSE_RANK() OVER (
				PARTITION BY
					CATEGORY
				ORDER BY
					DISCOUNTED_SELLING_PRICE * QUANTITY DESC
			) AS CATEGORY_RANK
		FROM
			PRODUCT_LEVEL_INVENTORY
		WHERE
			OUT_OF_STOCK = 'FALSE'
	)
SELECT
	*
FROM
	RANKED_PRODUCTS
WHERE
	CATEGORY_RANK <= 3
ORDER BY
	CATEGORY,
	CATEGORY_RANK asc;


--Category Concentration

SELECT
	CATEGORY,
	SUM(DISCOUNTED_SELLING_PRICE * QUANTITY) AS CATEGORY_WISE_REVENUE
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	OUT_OF_STOCK = 'TRUE'
GROUP BY
	CATEGORY
ORDER BY
	CATEGORY_WISE_REVENUE DESC;


-- % revenue contribution of each product to its category

WITH
	PRODUCT_REVENUE AS (
		SELECT
			CATEGORY,
			PRODUCT,
			(DISCOUNTED_SELLING_PRICE * AVAILABLE_QUANTITY) AS EACH_PRODUCT_REVENUE
		FROM
			PRODUCT_LEVEL_INVENTORY
	)
SELECT
	CATEGORY,
	PRODUCT,
	EACH_PRODUCT_REVENUE,
	SUM(EACH_PRODUCT_REVENUE) OVER (
		PARTITION BY
			CATEGORY
	) AS CATEGORY_WISE_TOTAL_REVENUE,
	ROUND(
		(
			EACH_PRODUCT_REVENUE * 100.0 / NULLIF(
				SUM(EACH_PRODUCT_REVENUE) OVER (
					PARTITION BY
						CATEGORY
				),
				0
			)
		),
		2
	) AS REVENUE_CONTRIBUTION_EACH_PRODUCT
FROM
	PRODUCT_REVENUE
ORDER BY
	CATEGORY,
	REVENUE_CONTRIBUTION_EACH_PRODUCT DESC;



--Inventory Risk Model...where the business is bleeding money

select product,category,mrp,discount_percent,available_quantity,out_of_stock from PRODUCT_LEVEL_INVENTORY 
where discount_percent>20
      and available_quantity<5
	  and out_of_stock = 'FALSE'
	  order by discount_percent desc;
	 

--Inventory Risk Model - "Luxury Anchors" (High MRP + Low Demand Proxy)

SELECT *
FROM (
    SELECT
        category,
        product,
        mrp,
        available_quantity,
        discount_percent,
        AVG(mrp) OVER (PARTITION BY category) AS category_avg_mrp
    FROM product_level_inventory
) 
WHERE
    mrp > category_avg_mrp
    AND available_quantity>2
    AND discount_percent >30
	ORDER BY available_quantity DESC;




                                     --Margin Leakage
									 
--High discount + low stock products

SELECT
	CATEGORY,
	PRODUCT,
	MRP,
	DISCOUNT_PERCENT,
	AVAILABLE_QUANTITY
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	DISCOUNT_PERCENT > 15
	AND AVAILABLE_QUANTITY < 3
	AND OUT_OF_STOCK = 'FALSE'
ORDER BY
	DISCOUNT_PERCENT DESC;



--Create price bands (Budget / Mid-range / Premium)/Count per segment/Revenue per segment/Average discount per segment

WITH
	PRICE_BAND AS (
		SELECT
			PRODUCT,
			CATEGORY,
			DISCOUNTED_SELLING_PRICE,
			AVAILABLE_QUANTITY,
			DISCOUNT_PERCENT,
			MRP,
			CASE
				WHEN MRP > 5000 THEN 'premium'
				WHEN MRP BETWEEN 2000 AND 5000  THEN 'MID_RANGE'
				ELSE 'BUDGET'
			END AS PRICE_BAND
		FROM
			PRODUCT_LEVEL_INVENTORY
	)
SELECT
	PRICE_BAND,
	COUNT(PRODUCT) AS PRODUCT_COUNT,
	SUM(DISCOUNTED_SELLING_PRICE * AVAILABLE_QUANTITY) AS POTENTIAN_REVENUE,
	ROUND(AVG(DISCOUNT_PERCENT), 2) AS AVG_DISCOUNT
FROM
	PRICE_BAND
GROUP BY
	PRICE_BAND;
						   
						   
--Stock Efficiency(High Stock + Low Discount)

SELECT
	CATEGORY,
	PRODUCT,
	MRP,
	AVAILABLE_QUANTITY,
	DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	AVAILABLE_QUANTITY = 6
	AND DISCOUNT_PERCENT = 0
	AND OUT_OF_STOCK = 'FALSE'
ORDER BY
	MRP DESC;


                                  --E-Commerce Pricing & Inventory Optimization Analysi


--count of Blank & Null rows/ Count missing names/Count negative prices/Count negative stock

SELECT
	SUM(
		CASE
			WHEN PRODUCT IS NULL THEN 1
			ELSE 0
		END
	) AS NULL_NAMES_COUNT,
	SUM(
		CASE
			WHEN MRP < 0 THEN 1
			ELSE 0
		END
	) AS NEGATIVE_MRP_COUNT,
	SUM(
		CASE
			WHEN AVAILABLE_QUANTITY < 0 THEN 1
			ELSE 0
		END
	) AS NEGATIVE_STOCK_COUNT
FROM
	PRODUCT_LEVEL_INVENTORY;



						   --KPI Dashboard Queries


--• Total products
--• Total categories
--• Total potential revenue
--• Average discount
--• Out-of-stock rate

SELECT
	COUNT(DISTINCT PRODUCT) AS TOTAL_PRODUCTS,
	count(DISTINCT CATEGORY) as total_categories,
	SUM(DISCOUNTED_SELLING_PRICE * AVAILABLE_QUANTITY) AS TOTAL_POTENTIAL_REVENUE,
	ROUND(AVG(DISCOUNT_PERCENT), 2) AS AVERAGE_DISCOUNT,
	SUM(
		CASE
			WHEN OUT_OF_STOCK = 'TRUE' THEN 1
			ELSE 0
		END
	) AS TOTAL_OUT_OF_STOCK_ITEMS
FROM
	PRODUCT_LEVEL_INVENTORY;


--Top 5 revenue categories

SELECT
	CATEGORY,
	SUM(DISCOUNTED_SELLING_PRICE * AVAILABLE_QUANTITY) AS CATEGORY_REVENUE from PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	CATEGORY_REVENUE DESC
LIMIT
	5;


--Most Over-Discounted Category

SELECT
	CATEGORY,
	ROUND(AVG(DISCOUNT_PERCENT), 2) AS AVG_CATEGORY_DISCOUNT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	AVG_CATEGORY_DISCOUNT DESC
LIMIT
	1;

--High-Risk Inventory Items

SELECT
	CATEGORY,
	PRODUCT,
	MRP,
	AVAILABLE_QUANTITY,
	DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	AVAILABLE_QUANTITY = 6
	AND MRP > 3000
	AND DISCOUNT_PERCENT > 15
	AND OUT_OF_STOCK = 'FALSE'
ORDER BY
	MRP DESC;

	
--Price-Per-Gram Premium Products

SELECT
	CATEGORY,
	PRODUCT,
	MRP,
	WEIGHT_IN_GMS,
	ROUND((MRP / WEIGHT_IN_GMS), 2) AS PRICE_PER_GRAM
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	WEIGHT_IN_GMS > 0
ORDER BY
	PRICE_PER_GRAM DESC
LIMIT
	10;




  
































