--Create price bands (Budget / Mid-range / Premium)/Count per segment/Revenue per segment/Average discount per segment

WITH
	PRICE_BAND AS (
		SELECT
			PRODUCT,
			CATEGORY,
			DISCOUNTED_SELLING_PRICE,
			AVAILABLE_QUANTITY,
			DISCOUNT_PERCENT,
			MRP,
			CASE
				WHEN MRP > 5000 THEN 'premium'
				WHEN MRP BETWEEN 2000 AND 5000  THEN 'MID_RANGE'
				ELSE 'BUDGET'
			END AS PRICE_BAND
		FROM
			PRODUCT_LEVEL_INVENTORY
	)
SELECT
	PRICE_BAND,
	COUNT(PRODUCT) AS PRODUCT_COUNT,
	SUM(DISCOUNTED_SELLING_PRICE * AVAILABLE_QUANTITY) AS POTENTIAN_REVENUE,
	ROUND(AVG(DISCOUNT_PERCENT), 2) AS AVG_DISCOUNT
FROM
	PRICE_BAND
GROUP BY
	PRICE_BAND;
						   
						   
--Stock Efficiency(High Stock + Low Discount)

SELECT
	CATEGORY,
	PRODUCT,
	MRP,
	AVAILABLE_QUANTITY,
	DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	AVAILABLE_QUANTITY = 6
	AND DISCOUNT_PERCENT = 0
	AND OUT_OF_STOCK = 'FALSE'
ORDER BY
	MRP DESC;


                                  --E-Commerce Pricing & Inventory Optimization Analysi


--count of Blank & Null rows/ Count missing names/Count negative prices/Count negative stock

SELECT
	SUM(
		CASE
			WHEN PRODUCT IS NULL THEN 1
			ELSE 0
		END
	) AS NULL_NAMES_COUNT,
	SUM(
		CASE
			WHEN MRP < 0 THEN 1
			ELSE 0
		END
	) AS NEGATIVE_MRP_COUNT,
	SUM(
		CASE
			WHEN AVAILABLE_QUANTITY < 0 THEN 1
			ELSE 0
		END
	) AS NEGATIVE_STOCK_COUNT
FROM
	PRODUCT_LEVEL_INVENTORY;



						   --KPI Dashboard Queries


--• Total products
--• Total categories
--• Total potential revenue
--• Average discount
--• Out-of-stock rate

SELECT
	COUNT(DISTINCT PRODUCT) AS TOTAL_PRODUCTS,
	count(DISTINCT CATEGORY) as total_categories,
	SUM(DISCOUNTED_SELLING_PRICE * AVAILABLE_QUANTITY) AS TOTAL_POTENTIAL_REVENUE,
	ROUND(AVG(DISCOUNT_PERCENT), 2) AS AVERAGE_DISCOUNT,
	SUM(
		CASE
			WHEN OUT_OF_STOCK = 'TRUE' THEN 1
			ELSE 0
		END
	) AS TOTAL_OUT_OF_STOCK_ITEMS
FROM
	PRODUCT_LEVEL_INVENTORY;


--Top 5 revenue categories

SELECT
	CATEGORY,
	SUM(DISCOUNTED_SELLING_PRICE * AVAILABLE_QUANTITY) AS CATEGORY_REVENUE from PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	CATEGORY_REVENUE DESC
LIMIT
	5;


--Most Over-Discounted Category

SELECT
	CATEGORY,
	ROUND(AVG(DISCOUNT_PERCENT), 2) AS AVG_CATEGORY_DISCOUNT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	AVG_CATEGORY_DISCOUNT DESC
LIMIT
	1;

--High-Risk Inventory Items

SELECT
	CATEGORY,
	PRODUCT,
	MRP,
	AVAILABLE_QUANTITY,
	DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	AVAILABLE_QUANTITY = 6
	AND MRP > 3000
	AND DISCOUNT_PERCENT > 15
	AND OUT_OF_STOCK = 'FALSE'
ORDER BY
	MRP DESC;

	
--Price-Per-Gram Premium Products

SELECT
	CATEGORY,
	PRODUCT,
	MRP,
	WEIGHT_IN_GMS,
	ROUND((MRP / WEIGHT_IN_GMS), 2) AS PRICE_PER_GRAM
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	WEIGHT_IN_GMS > 0
ORDER BY
	PRICE_PER_GRAM DESC
LIMIT
	10;