DROP TABLE IF EXISTS PRODUCT_LEVEL_INVENTORY;


CREATE TABLE PRODUCT_LEVEL_INVENTORY (
	CATEGORY VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	MRP INT NOT NULL,
	DISCOUNT_PERCENT INT NOT NULL,
	AVAILABLE_QUANTITY INT NOT NULL,
	DISCOUNTED_SELLING_PRICE INT NOT NULL,
	WEIGHT_IN_GMS INT NOT NULL,
	OUT_OF_STOCK VARCHAR(50) NOT NULL,
	QUANTITY INT
);

select * from product_level_inventory;


COPY PRODUCT_LEVEL_INVENTORY (
	CATEGORY,
	NAME,
	MRP,
	DISCOUNT_PERCENT,
	AVAILABLE_QUANTITY,
	DISCOUNTED_SELLING_PRICE,
	WEIGHT_IN_GMS,
	OUT_OF_STOCK,
	QUANTITY
)
FROM
	'C:\Users\kaif\OneDrive\Desktop\zepto_v1111.csv' DELIMITER ',' CSV HEADER;

SELECT
	*
FROM
	PRODUCT_LEVEL_INVENTORY;


                                   --View all products

--View all products

SELECT
	NAME
FROM
	PRODUCT_LEVEL_INVENTORY;
	

 -- Limit 10 rows
 
 SELECT
	*
FROM
	PRODUCT_LEVEL_INVENTORY
LIMIT
	10;
	

 --Category-level listing

SELECT DISTINCT
	CATEGORY
FROM
	PRODUCT_LEVEL_INVENTORY;
	

--Count products per category

SELECT
	CATEGORY,
	COUNT(*) AS TOTAL_PRODUCTS
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	TOTAL_PRODUCTS DESC;


									--Price Analysis

--Top 10 highest MRP products	

SELECT
	NAME,
	CATEGORY,
	MRP
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	MRP DESC
LIMIT
	10;

--Top 10 lowest discounted price products

SELECT
	NAME,
	CATEGORY,
	DISCOUNTED_SELLING_PRICE
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	DISCOUNTED_SELLING_PRICE ASC
LIMIT
	10;


--Average MRP per category

SELECT
	CATEGORY,
	ROUND(AVG(MRP), 3) AS AVG_MRP_PER_CATEGORY
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY;


                                --Stock Status

--Count out-of-stock products

SELECT
	CATEGORY,
	product,
	COUNT(*) AS OUT_OF_STOCK_COUNT
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	OUT_OF_STOCK = 'TRUE'
GROUP BY
	CATEGORY,
	product;

--Show products where availableQuantity < 5

ALTER TABLE PRODUCT_LEVEL_INVENTORY
RENAME NAME TO PRODUCT;

SELECT
	*
FROM
	PRODUCT_LEVEL_INVENTORY;

SELECT
	PRODUCT,
	AVAILABLE_QUANTITY
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	AVAILABLE_QUANTITY < 5;


--Percentage of out-of-stock products

SELECT
	COUNT(
		CASE
			WHEN OUT_OF_STOCK = 'TRUE' THEN 1
		END
	) * 100.0 / COUNT(*) AS OUT_OF_STOCK_PERCENTAGE
FROM
	PRODUCT_LEVEL_INVENTORY;

                                       -- Discount Insights


--Products with discount > 20%

SELECT
	CATEGORY,
	DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	DISCOUNT_PERCENT > 21
ORDER BY
	DISCOUNT_PERCENT DESC;

--Average discount per category

SELECT
	CATEGORY,
	ROUND(AVG(DISCOUNT_PERCENT), 2) AS CATEGORY_DISCOUNT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY;

--Highest  discounted product

SELECT
	PRODUCT,
	CATEGORY,
	DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	DISCOUNT_PERCENT DESC
LIMIT
	1;
