--Estimated profit per product (Cost = 70% of MRP)
SELECT
	PRODUCT,
	MRP,
	ROUND(MRP * 0.30, 2) AS PROFIT_MARGIN
FROM
	PRODUCT_LEVEL_INVENTORY
	ORDER BY PROFIT_MARGIN DESC;



		 
--Category-wise profit

SELECT
	*
FROM
	PRODUCT_LEVEL_INVENTORY;

ALTER TABLE PRODUCT_LEVEL_INVENTORY
ADD COLUMN TOTAL_PROFIT NUMERIC(10, 2);

UPDATE PRODUCT_LEVEL_INVENTORY
SET
	TOTAL_PROFIT = MRP * 0.30;

SELECT
	CATEGORY,
	SUM(TOTAL_PROFIT) AS CATEGORY_WISE_PROFIT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	CATEGORY_WISE_PROFIT DESC;


                                         --Discount Impact Analysis	
										 

--Compare average MRP vs average discounted price by category

SELECT
	CATEGORY,
	ROUND(AVG(MRP), 3) AS AVG_MRP,
	ROUND(AVG(DISCOUNT_PERCENT), 3) AS AVG_DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	(CATEGORY);


--Category with highest average discount
SELECT
	CATEGORY,
	ROUND(AVG(DISCOUNT_PERCENT), 3) AS AVG_DISCOUNT_PERCENT
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	(CATEGORY);


--Correlation between discountPercent and availableQuantity

SELECT
	PRODUCT,
	DISCOUNT_PERCENT,
	AVAILABLE_QUANTITY
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	DISCOUNT_PERCENT,
	AVAILABLE_QUANTITY DESC;

SELECT
	CATEGORY,
	CORR(DISCOUNT_PERCENT, AVAILABLE_QUANTITY) AS CORRELATION_VALUE
FROM
	PRODUCT_LEVEL_INVENTORY
GROUP BY
	CATEGORY
ORDER BY
	CORRELATION_VALUE DESC;

  --all correlation_values are random--


--Weight-Based Pricing

SELECT
	PRODUCT,
	WEIGHT_IN_GMS,
	MRP
FROM
	PRODUCT_LEVEL_INVENTORY
ORDER BY
	WEIGHT_IN_GMS DESC;


--Price per gram calculation
SELECT
	WEIGHT_IN_GMS
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	WEIGHT_IN_GMS = 0;


SELECT
	PRODUCT,
	MRP,
	WEIGHT_IN_GMS,
	MRP / NULLIF(WEIGHT_IN_GMS, 0) AS PRICE_PER_GRAM
FROM
	PRODUCT_LEVEL_INVENTORY;
    


--Most expensive per gram products

SELECT
	PRODUCT,
	MRP,
	WEIGHT_IN_GMS,
	MRP / WEIGHT_IN_GMS AS PRICE_PER_GRAM
FROM
	PRODUCT_LEVEL_INVENTORY
WHERE
	MRP IS NOT NULL
	AND WEIGHT_IN_GMS IS NOT NULL
	AND WEIGHT_IN_GMS <> 0
ORDER BY
	PRICE_PER_GRAM DESC;
  
--Cheapest per gram products
SELECT
	PRODUCT,
	MRP,
	WEIGHT_IN_GMS,
	MRP / WEIGHT_IN_GMS AS PRICE_PER_GRAM
FROM	
	PRODUCT_LEVEL_INVENTORY
WHERE
	MRP IS NOT NULL
	AND WEIGHT_IN_GMS IS NOT NULL
	AND WEIGHT_IN_GMS <> 0
ORDER BY
	PRICE_PER_GRAM ASC;